export type Role = 'ADMIN' | 'GESTOR' | 'OPERADOR' | 'TECNICO' | 'VENDEDOR' | 'COMERCIAL'

export interface Permission {
  verDashboard:      boolean
  verChamados:       boolean
  verEquipes:        boolean
  verMapa:           boolean
  verEstoque:        boolean
  verVendas:         boolean
  verRelatorios:     boolean
  verAuditoria:      boolean
  verUsuarios:       boolean
  verConfiguracoes:  boolean
  verTV:             boolean
  verFinanceiro:     boolean
  verSolicitacoes:   boolean
  verPonto:          boolean
  verHorasExtras:    boolean
  verClientes:       boolean
  verMapaInmap:      boolean
  verSmartOLT:       boolean
  verLinkDedicado:   boolean
 verCombustivel:    boolean
  verMinhaComissao:  boolean
  aprovarVendas:     boolean
  aprovarDevolucoes: boolean
  editarUsuarios:    boolean
  excluirRegistros:  boolean
  apenasMinhaEquipe: boolean
  verDesempenho:     boolean
  analisarAvaliacoes: boolean
}

const PERMISSIONS_MAP: Record<Role, Permission> = {
  ADMIN: {
    verDashboard:      true,
    verChamados:       true,
    verEquipes:        true,
    verMapa:           true,
    verEstoque:        true,
    verVendas:         true,
    verRelatorios:     true,
    verAuditoria:      true,
    verUsuarios:       true,
    verConfiguracoes:  true,
    verTV:             true,
    verFinanceiro:     true,
    verSolicitacoes:   true,
    verPonto:          false,
    verHorasExtras:    true,
    verClientes:       true,
    verMapaInmap:      true,
    verSmartOLT:       true,
    verLinkDedicado:   true,
    verCombustivel:    true,
    verMinhaComissao:  false,
    aprovarVendas:     true,
    aprovarDevolucoes: true,
    editarUsuarios:    true,
    excluirRegistros:  true,
    apenasMinhaEquipe: false,
    verDesempenho:     true,
    analisarAvaliacoes: true,
  },
  GESTOR: {
    verDashboard:      true,
    verChamados:       true,
    verEquipes:        true,
    verMapa:           true,
    verEstoque:        true,
    verVendas:         true,
    verRelatorios:     true,
    verAuditoria:      true,
    verUsuarios:       false,
    verConfiguracoes:  false,
    verTV:             true,
    verFinanceiro:     true,
    verSolicitacoes:   true,
    verPonto:          false,
    verHorasExtras:    true,
    verClientes:       true,
    verMapaInmap:      true,
    verSmartOLT:       true,
    verLinkDedicado:   true,
    verCombustivel:    true,
    verMinhaComissao:  false,
    aprovarVendas:     true,
    aprovarDevolucoes: true,
    editarUsuarios:    false,
    excluirRegistros:  false,
    apenasMinhaEquipe: false,
    verDesempenho:     true,
    analisarAvaliacoes: false,
  },
  OPERADOR: {
    verDashboard:      true,
    verChamados:       true,
    verEquipes:        true,
    verMapa:           true,
    verEstoque:        true,
    verVendas:         true,
    verRelatorios:     false,
    verAuditoria:      false,
    verUsuarios:       false,
    verConfiguracoes:  false,
    verTV:             true,
    verFinanceiro:     true,
    verSolicitacoes:   false,
    verPonto:          false,
    verHorasExtras:    false,
    verClientes:       true,
    verMapaInmap:      true,
    verSmartOLT:       true,
    verLinkDedicado:   true,
    verCombustivel:    false,
    verMinhaComissao:  true,
    aprovarVendas:     false,
    aprovarDevolucoes: false,
    editarUsuarios:    false,
    excluirRegistros:  false,
    apenasMinhaEquipe: false,
    verDesempenho:     false,
    analisarAvaliacoes: false,
  },
  COMERCIAL: {
    verDashboard:      true,
    verChamados:       true,
    verEquipes:        true,
    verMapa:           true,
    verEstoque:        true,
    verVendas:         true,
    verRelatorios:     false,
    verAuditoria:      false,
    verUsuarios:       false,
    verConfiguracoes:  false,
    verTV:             true,
    verFinanceiro:     true,
    verSolicitacoes:   false,
    verPonto:          false,
    verHorasExtras:    false,
    verClientes:       true,
    verMapaInmap:      false,
    verSmartOLT:       false,
    verLinkDedicado:   false,
    verCombustivel:    false,
    verMinhaComissao:  false,
    aprovarVendas:     false,
    aprovarDevolucoes: false,
    editarUsuarios:    false,
    excluirRegistros:  false,
    apenasMinhaEquipe: false,
    verDesempenho:     false,
    analisarAvaliacoes: false,
  },
  TECNICO: {
    verDashboard:      false,
    verChamados:       true,
    verEquipes:        true,
    verMapa:           false,
    verEstoque:        false,
    verVendas:         false,
    verRelatorios:     false,
    verAuditoria:      false,
    verUsuarios:       false,
    verConfiguracoes:  false,
    verTV:             false,
    verFinanceiro:     false,
    verSolicitacoes:   false,
    verPonto:          true,
    verHorasExtras:    false,
    verClientes:       false,
    verMapaInmap:      true,
    verSmartOLT:       false,
    verLinkDedicado:   false,
    verCombustivel:    false,
    verMinhaComissao:  false,
    aprovarVendas:     false,
    aprovarDevolucoes: false,
    editarUsuarios:    false,
    excluirRegistros:  false,
    apenasMinhaEquipe: true,
    verDesempenho:     false,
    analisarAvaliacoes: false,
  },
  VENDEDOR: {
    verDashboard:      true,
    verChamados:       false,
    verEquipes:        false,
    verMapa:           false,
    verEstoque:        false,
    verVendas:         true,
    verRelatorios:     false,
    verAuditoria:      false,
    verUsuarios:       false,
    verConfiguracoes:  false,
    verTV:             false,
    verFinanceiro:     false,
    verSolicitacoes:   false,
    verPonto:          false,
    verHorasExtras:    false,
    verClientes:       false,
    verMapaInmap:      false,
    verSmartOLT:       false,
    verLinkDedicado:   false,
    verCombustivel:    false,
    verMinhaComissao:  true,
    aprovarVendas:     false,
    aprovarDevolucoes: false,
    editarUsuarios:    false,
    excluirRegistros:  false,
    apenasMinhaEquipe: false,
    verDesempenho:     false,
    analisarAvaliacoes: false,
  },
}

export function getPermissions(role: string): Permission {
  return PERMISSIONS_MAP[role as Role] || PERMISSIONS_MAP.OPERADOR
}

export function temPermissao(role: string, permissao: keyof Permission): boolean {
  return getPermissions(role)[permissao] as boolean
}